# language: ruby

sudo: false

dist: precise

# cache: bundler

env:
  - DIST=precise STACK=EC2

# matrix:
#   include:
#     - sudo: required
#       dist: precise
#       env: DIST=precise STACK=GCE
#     - sudo: false
#       dist: trusty
#       env: DIST=trusty STACK=EC2
#     - sudo: required
#       dist: trusty
#       env: DIST=trusty STACK=GCE
#     - os: osx
#       osx_image: xcode8.3
#       env: RELEASE=sierra
#     - os: osx
#       env: RELEASE=default

language: generic
jobs:
  include:
    - stage: "1"
      script: sh -c true
    - stage: "2"
      script: sh -c true
    - stage: "3"
      script: sh -c true
    - stage: "4"
      script: sh -c true
    - stage: "5"
      script: sh -c true
    - stage: "6"
      script: sh -c true
    - stage: "7"
      script: sh -c true
    - stage: "8"
      script: sh -c true
    - stage: "9"
      script: sh -c true
    - stage: "10"
      script: sh -c true
    - stage: "11"
      script: sh -c true
    - stage: "12"
      script: sh -c true
    - stage: "13"
      script: sh -c true
    - stage: "14"
      script: sh -c true
    - stage: "15"
      script: sh -c true
    - stage: "16"
      script: sh -c true
    - stage: "17"
      script: sh -c true
    - stage: "18"
      script: sh -c true
    - stage: "19"
      script: sh -c true
    - stage: "20"
      script: sh -c true

install:
  - true

script: cat ~/build.sh

notifications:
  email: false
  # webhooks: http://requestb.in/16le4he1

  #  slack:
  #  rooms:
  #    - secure: "KZTfjxhkOdDDZYD2ThBILt2ShYtdEee3PudFZlQBfpxG9N470GfxnKVfOl7Odu4lN6cIupwC4S4BnehubEywSR99l60VmfhePUCTqDLYy+iR9+guTvaECdXdaau3jTKhFdu5u60ITsiw5Yb+hwAaGFO0HmQhqR9XVr/U8IGQlok="
  #  template:
  #    - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository}@%{branch} by %{author} %{result} in %{duration} (elapsed time: %{elapsed_time}) subject: %{commit_subject} message: %{commit_message} foobar"
  #  on_success: always
